repos:
  # general checks & fixes
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: check-yaml
        args: ["--unsafe"]
      - id: check-json
      - id: pretty-format-json
        args: ["--autofix"]
      - id: check-merge-conflict
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: check-added-large-files

  # lint markdown
  - repo: https://github.com/igorshubovych/markdownlint-cli
    rev: v0.38.0
    hooks:
      - id: markdownlint
        name: Lint markdown
        args: ["--fix"]

  # lint & format python, enforce python coding standards, sort python imports
  - repo: https://github.com/charliermarsh/ruff-pre-commit
    rev: "v0.1.14"
    hooks:
      - id: ruff
        args: [--fix]
      - id: ruff-format
