AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: A Serverless application with shared REST API Gateway and multiple Lambda modules.

Resources:
  SharedRestApi:
    Type: AWS::Serverless::Api
    Properties:
      StageName: dev

  SQSQueue:
    Type: AWS::SQS::Queue
    Properties:
      QueueName: SQSQueue

  AuthenticateFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: backend/auth
      Handler: com.bookanaudio.StreamLambdaHandler::handleRequest
      Runtime: java17
      MemorySize: 256
      Timeout: 30
      Architectures:
        - x86_64
      EphemeralStorage:
        Size: 512
      Environment:
        Variables:
          s3_bucket_name: "bookanaudio"
          google_token_endpoint: "https://oauth2.googleapis.com/token"
          jwt_expiration: "36000000"
          jwt_secret_key: "QDoBBK26MGfreN7+fduLGfdQb0xZYznT+sAnMQTrshA"
          google_client_id: "284511919951-m302te4ql07i61nnc1l2h4n4ld1s2skq.apps.googleusercontent.com"
          iam_access_key: "AKIARHQBNF6UE4BWXTHR"
          DB_URL: "jdbc:postgresql://bookanaudio.cluster-c54es4ekqdow.eu-north-1.rds.amazonaws.com:5432/bookanaudio"
          google_redirect_uri: "http://localhost:8080/auth/oauth/callback"
          DB_USERNAME: "mohammed"
          google_user_info_endpoint: "https://www.googleapis.com/oauth2/v2/userinfo"
          iam_secret_key: "T7IWpZ8FvB4QCe/VxwwiggW3Xx35ydCbeWq2PdSw"
          DB_PASSWORD: "12345"
          google_client_secret: "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"
          aws_region: "eu-north-1"
      EventInvokeConfig:
        MaximumEventAgeInSeconds: 21600
        MaximumRetryAttempts: 2
      PackageType: Zip
      Policies:
        - Statement:
            - Effect: Allow
              Action:
                - logs:CreateLogGroup
              Resource: arn:aws:logs:eu-north-1:084828565416:*
            - Effect: Allow
              Action:
                - logs:CreateLogStream
                - logs:PutLogEvents
              Resource: arn:aws:logs:eu-north-1:084828565416:log-group:/aws/lambda/authenticate:*
            - Effect: Allow
              Action:
                - ec2:DescribeNetworkInterfaces
                - ec2:CreateNetworkInterface
                - ec2:DeleteNetworkInterface
                - ec2:DescribeInstances
                - ec2:AttachNetworkInterface
              Resource: '*'
      VpcConfig:
        SecurityGroupIds:
          - sg-063f0bf0ff3291693
          - sg-04d27e332409719bc
          - sg-0281fd02a523fd6db
        SubnetIds:
          - subnet-02ce3eebf7110a947
      Events:
        ApiAuthLogin:
          Type: Api
          Properties:
            RestApiId: !Ref SharedRestApi
            Path: /auth/login
            Method: POST
        ApiAuthRegister:
          Type: Api
          Properties:
            RestApiId: !Ref SharedRestApi
            Path: /auth/register
            Method: POST
        ApiAuthVerify:
          Type: Api
          Properties:
            RestApiId: !Ref SharedRestApi
            Path: /auth/verify
            Method: GET

  BooksFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: backend/books
      Handler: com.bookanaudio.StreamLambdaHandler::handleRequest
      Runtime: java17
      MemorySize: 256
      Timeout: 30
      Architectures:
        - x86_64
      EphemeralStorage:
        Size: 512
      Environment:
        Variables:
          s3_bucket_name: "bookanaudio"
          google_token_endpoint: "https://oauth2.googleapis.com/token"
          jwt_expiration: "36000000"
          jwt_secret_key: "QDoBBK26MGfreN7+fduLGfdQb0xZYznT+sAnMQTrshA"
          google_client_id: "284511919951-m302te4ql07i61nnc1l2h4n4ld1s2skq.apps.googleusercontent.com"
          iam_access_key: "AKIARHQBNF6UE4BWXTHR"
          DB_URL: "jdbc:postgresql://bookanaudio.cluster-c54es4ekqdow.eu-north-1.rds.amazonaws.com:5432/bookanaudio"
          google_redirect_uri: "http://localhost:8080/auth/oauth/callback"
          DB_USERNAME: "mohammed"
          google_user_info_endpoint: "https://www.googleapis.com/oauth2/v2/userinfo"
          iam_secret_key: "T7IWpZ8FvB4QCe/VxwwiggW3Xx35ydCbeWq2PdSw"
          DB_PASSWORD: "12345"
          google_client_secret: "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"
          aws_region: "eu-north-1"
          sqs_url: "https://sqs.eu-north-1.amazonaws.com/084828565416/SQSQueue" 
      EventInvokeConfig:
        MaximumEventAgeInSeconds: 21600
        MaximumRetryAttempts: 2
      PackageType: Zip
      Policies:
        - AWSLambdaBasicExecutionRole
        - Statement:
            - Effect: Allow
              Action:
                - sqs:SendMessage
              Resource: !GetAtt SQSQueue.Arn
      VpcConfig:
        SecurityGroupIds:
          - sg-063f0bf0ff3291693
          - sg-04d27e332409719bc
          - sg-0281fd02a523fd6db
        SubnetIds:
          - subnet-02ce3eebf7110a947
      Events:
        ApiGetBooks:
          Type: Api
          Properties:
            RestApiId: !Ref SharedRestApi
            Path: /books
            Method: GET
        CheckNet:
          Type: Api
          Properties:
            RestApiId: !Ref SharedRestApi
            Path: /books/check-net
            Method: GET
        ApiPostBook:
          Type: Api
          Properties:
            RestApiId: !Ref SharedRestApi
            Path: /books
            Method: POST
        ApiFilterBooks:
          Type: Api
          Properties:
            RestApiId: !Ref SharedRestApi
            Path: /books/filter
            Method: GET
        ApiGetSignedUrl:
          Type: Api
          Properties:
            RestApiId: !Ref SharedRestApi
            Path: /books/pre-signed-url
            Method: GET

  PagesFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: backend/pages
      Handler: com.bookanaudio.StreamLambdaHandler::handleRequest
      Runtime: java17
      MemorySize: 256
      Timeout: 30
      Architectures:
        - x86_64
      EphemeralStorage:
        Size: 512
      Environment:
        Variables:
          s3_bucket_name: "bookanaudio"
          google_token_endpoint: "https://oauth2.googleapis.com/token"
          jwt_expiration: "36000000"
          jwt_secret_key: "QDoBBK26MGfreN7+fduLGfdQb0xZYznT+sAnMQTrshA"
          google_client_id: "284511919951-m302te4ql07i61nnc1l2h4n4ld1s2skq.apps.googleusercontent.com"
          iam_access_key: "AKIARHQBNF6UE4BWXTHR"
          DB_URL: "jdbc:postgresql://bookanaudio.cluster-c54es4ekqdow.eu-north-1.rds.amazonaws.com:5432/bookanaudio"
          google_redirect_uri: "http://localhost:8080/auth/oauth/callback"
          DB_USERNAME: "mohammed"
          google_user_info_endpoint: "https://www.googleapis.com/oauth2/v2/userinfo"
          iam_secret_key: "T7IWpZ8FvB4QCe/VxwwiggW3Xx35ydCbeWq2PdSw"
          DB_PASSWORD: "12345"
          google_client_secret: "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"
          aws_region: "eu-north-1"
          sqs_url: "https://sqs.eu-north-1.amazonaws.com/084828565416/SQSQueue" 
      EventInvokeConfig:
        MaximumEventAgeInSeconds: 21600
        MaximumRetryAttempts: 2
      PackageType: Zip
      Policies:
        - AWSLambdaBasicExecutionRole
      VpcConfig:
        SecurityGroupIds:
          - sg-063f0bf0ff3291693
          - sg-04d27e332409719bc
          - sg-0281fd02a523fd6db
        SubnetIds:
          - subnet-02ce3eebf7110a947
      Events:
        ApiGetPages:
          Type: Api
          Properties:
            RestApiId: !Ref SharedRestApi
            Path: /books/{book_id}/pages
            Method: GET
        ApiPostPage:
          Type: Api
          Properties:
            RestApiId: !Ref SharedRestApi
            Path: /books/{book_id}/pages
            Method: POST

  S3Function:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: backend/s3
      Handler: com.bookanaudio.AwsLambdaSqsFunctionHandler
      Runtime: java17
      MemorySize: 256
      Timeout: 30
      Architectures:
        - x86_64
      Environment:
        Variables:
          s3_bucket_name: "bookanaudio"
          google_token_endpoint: "https://oauth2.googleapis.com/token"
          jwt_expiration: "36000000"
          jwt_secret_key: "QDoBBK26MGfreN7+fduLGfdQb0xZYznT+sAnMQTrshA"
          google_client_id: "284511919951-m302te4ql07i61nnc1l2h4n4ld1s2skq.apps.googleusercontent.com"
          iam_access_key: "AKIARHQBNF6UE4BWXTHR"
          DB_URL: "jdbc:postgresql://bookanaudio.cluster-c54es4ekqdow.eu-north-1.rds.amazonaws.com:5432/bookanaudio"
          google_redirect_uri: "http://localhost:8080/auth/oauth/callback"
          DB_USERNAME: "mohammed"
          google_user_info_endpoint: "https://www.googleapis.com/oauth2/v2/userinfo"
          iam_secret_key: "T7IWpZ8FvB4QCe/VxwwiggW3Xx35ydCbeWq2PdSw"
          DB_PASSWORD: "12345"
          google_client_secret: "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"
          aws_region: "eu-north-1"
          sqs_url: "https://sqs.eu-north-1.amazonaws.com/084828565416/SQSQueue"
      EventInvokeConfig:
        MaximumEventAgeInSeconds: 21600
        MaximumRetryAttempts: 2
      PackageType: Zip
      Policies:
        - AWSLambdaBasicExecutionRole
        - Statement:
            - Effect: Allow
              Action:
                - s3:GetObject
                - s3:PutObject
              Resource: arn:aws:s3:::bookanaudio/*
        - Statement:
            - Effect: Allow
              Action:
                - sqs:SendMessage
              Resource: arn:aws:sqs:eu-north-1:084828565416:SQSQueue
      VpcConfig:
        SecurityGroupIds:
          - sg-063f0bf0ff3291693
          - sg-04d27e332409719bc
          - sg-0281fd02a523fd6db
        SubnetIds:
          - subnet-02ce3eebf7110a947
      Events:
        S3QueueEvent:
          Type: SQS
          Properties:
            Queue: arn:aws:sqs:eu-north-1:084828565416:SQSQueue

Outputs:
  ApiUrl:
    Description: URL for the API Gateway stage
    Value: !Sub "https://${SharedRestApi}.execute-api.${AWS::Region}.amazonaws.com/dev/"
