CREATE TABLE pages (
    id SERIAL PRIMARY KEY,
    page_number INTEGER NOT NULL,
    book_id INTEGER NOT NULL REFERENCES books(id) ON DELETE CASCADE,
    s3_url VARCHAR(255) NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    chapter VARCHAR(10)
);
