name: CI - Pages Module

on:
  push:
    paths:
      - 'backend/pages/**'
      - '.github/workflows/pages.yml'

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Run Tests for Pages Module
        run: |
          cd backend/pages
          mvn clean test
